-- Core roles, databases, and schemas with access roles for the SALES data product

-- ============================================================================
-- CORE ROLES & DATABASE SETUP
-- Data Product: SALES | Zones: RAW, CURATED, CONSUMPTION
-- ============================================================================

-- =============================================================================
-- STEP 1: Core Account-Level Roles
-- =============================================================================

CREATE ROLE IF NOT EXISTS SALES_ADMIN
  COMMENT = 'Admin role for the SALES data product';

CREATE ROLE IF NOT EXISTS SALES_ENGINEER
  COMMENT = 'Engineer role for the SALES data product';

CREATE ROLE IF NOT EXISTS SALES_ANALYST
  COMMENT = 'Analyst role for the SALES data product';

-- Role hierarchy: ADMIN > ENGINEER > ANALYST
GRANT ROLE SALES_ANALYST TO ROLE SALES_ENGINEER;
GRANT ROLE SALES_ENGINEER TO ROLE SALES_ADMIN;
GRANT ROLE SALES_ADMIN TO ROLE SYSADMIN;

-- =============================================================================
-- STEP 2: Create Databases for Each Zone
-- =============================================================================
CREATE DATABASE IF NOT EXISTS SALES_RAW
  COMMENT = 'Raw/landing zone for SALES data product';

CREATE DATABASE IF NOT EXISTS SALES_CURATED
  COMMENT = 'Curated/transformed zone for SALES data product';

CREATE DATABASE IF NOT EXISTS SALES_CONSUMPTION
  COMMENT = 'Consumption zone for SALES data product';

GRANT OWNERSHIP ON DATABASE SALES_RAW TO ROLE SALES_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE SALES_CURATED TO ROLE SALES_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE SALES_CONSUMPTION TO ROLE SALES_ADMIN COPY CURRENT GRANTS;

-- =============================================================================
-- STEP 3: Schemas and Access Roles - SALES_RAW
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS SALES_RAW.DEFAULT
  COMMENT = 'Default schema for raw data';
CREATE SCHEMA IF NOT EXISTS SALES_RAW.STAGING
  COMMENT = 'Staging schema for intermediate raw processing';
CREATE SCHEMA IF NOT EXISTS SALES_RAW.ARCHIVE
  COMMENT = 'Archive schema for historical raw data';

CREATE ROLE IF NOT EXISTS SALES_RAW_READ
  COMMENT = 'Read access to all SALES_RAW schemas';
CREATE ROLE IF NOT EXISTS SALES_RAW_WRITE
  COMMENT = 'Write access to all SALES_RAW schemas';

GRANT USAGE ON DATABASE SALES_RAW TO ROLE SALES_RAW_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_RAW TO ROLE SALES_RAW_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE SALES_RAW TO ROLE SALES_RAW_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SALES_RAW TO ROLE SALES_RAW_READ;

GRANT USAGE ON DATABASE SALES_RAW TO ROLE SALES_RAW_WRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_RAW TO ROLE SALES_RAW_WRITE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SALES_RAW TO ROLE SALES_RAW_WRITE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE SALES_RAW TO ROLE SALES_RAW_WRITE;

GRANT ROLE SALES_RAW_READ TO ROLE SALES_RAW_WRITE;
GRANT ROLE SALES_RAW_WRITE TO ROLE SALES_ENGINEER;

-- =============================================================================
-- STEP 4: Schemas and Access Roles - SALES_CURATED
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS SALES_CURATED.DEFAULT
  COMMENT = 'Default schema for curated data';
CREATE SCHEMA IF NOT EXISTS SALES_CURATED.STAGING
  COMMENT = 'Staging schema for intermediate curated processing';
CREATE SCHEMA IF NOT EXISTS SALES_CURATED.ARCHIVE
  COMMENT = 'Archive schema for historical curated data';

CREATE ROLE IF NOT EXISTS SALES_CURATED_READ
  COMMENT = 'Read access to all SALES_CURATED schemas';
CREATE ROLE IF NOT EXISTS SALES_CURATED_WRITE
  COMMENT = 'Write access to all SALES_CURATED schemas';

GRANT USAGE ON DATABASE SALES_CURATED TO ROLE SALES_CURATED_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_CURATED TO ROLE SALES_CURATED_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE SALES_CURATED TO ROLE SALES_CURATED_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SALES_CURATED TO ROLE SALES_CURATED_READ;

GRANT USAGE ON DATABASE SALES_CURATED TO ROLE SALES_CURATED_WRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_CURATED TO ROLE SALES_CURATED_WRITE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SALES_CURATED TO ROLE SALES_CURATED_WRITE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE SALES_CURATED TO ROLE SALES_CURATED_WRITE;

GRANT ROLE SALES_CURATED_READ TO ROLE SALES_CURATED_WRITE;
GRANT ROLE SALES_CURATED_WRITE TO ROLE SALES_ENGINEER;

-- =============================================================================
-- STEP 5: Schemas and Access Roles - SALES_CONSUMPTION
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS SALES_CONSUMPTION.DEFAULT
  COMMENT = 'Default schema for consumption-ready data';
CREATE SCHEMA IF NOT EXISTS SALES_CONSUMPTION.STAGING
  COMMENT = 'Staging schema for intermediate consumption processing';
CREATE SCHEMA IF NOT EXISTS SALES_CONSUMPTION.ARCHIVE
  COMMENT = 'Archive schema for historical consumption data';

CREATE ROLE IF NOT EXISTS SALES_CONSUMPTION_READ
  COMMENT = 'Read access to all SALES_CONSUMPTION schemas';
CREATE ROLE IF NOT EXISTS SALES_CONSUMPTION_WRITE
  COMMENT = 'Write access to all SALES_CONSUMPTION schemas';

GRANT USAGE ON DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_READ;

GRANT USAGE ON DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_WRITE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_WRITE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_WRITE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE SALES_CONSUMPTION TO ROLE SALES_CONSUMPTION_WRITE;

GRANT ROLE SALES_CONSUMPTION_READ TO ROLE SALES_CONSUMPTION_WRITE;
GRANT ROLE SALES_CONSUMPTION_WRITE TO ROLE SALES_ENGINEER;

-- Analysts get read access to consumption zone only
GRANT ROLE SALES_CONSUMPTION_READ TO ROLE SALES_ANALYST;
