-- Consumer access: custom read roles and database grants for external consumers

-- ============================================================================
-- CONSUMER ACCESS
-- Role: ANALYTICS_READER | Databases: ANALYTICS, DATA_PRODUCTS, SHARED_DATA
-- ============================================================================

-- =============================================================================
-- STEP 1: Create Custom Read Role
-- =============================================================================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ANALYTICS_READER
  COMMENT = 'Read-only role for external data product consumers';

-- Grant the role to SYSADMIN for hierarchy management
GRANT ROLE ANALYTICS_READER TO ROLE SYSADMIN;

-- Grant warehouse usage for query execution
GRANT USAGE ON WAREHOUSE XS_WH TO ROLE ANALYTICS_READER;

-- =============================================================================
-- STEP 2: Grant Database Access
-- =============================================================================

-- ANALYTICS database
GRANT USAGE ON DATABASE ANALYTICS TO ROLE ANALYTICS_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE ANALYTICS_READER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE ANALYTICS_READER;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO ROLE ANALYTICS_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE ANALYTICS_READER;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS TO ROLE ANALYTICS_READER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS TO ROLE ANALYTICS_READER;

-- DATA_PRODUCTS database
GRANT USAGE ON DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;
GRANT SELECT ON ALL TABLES IN DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;
GRANT SELECT ON ALL VIEWS IN DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DATA_PRODUCTS TO ROLE ANALYTICS_READER;

-- SHARED_DATA database
GRANT USAGE ON DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
GRANT SELECT ON ALL TABLES IN DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
GRANT SELECT ON ALL VIEWS IN DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SHARED_DATA TO ROLE ANALYTICS_READER;
